### ISSUE TITLE
Any pxt-giggle block using the accelerometer gives 050 error on the micro bit

### ISSUE THREAD

**Issue by smsm1** [DexterInd/pxt-giggle#21]
Anytime I try and use a block from this package that requires use of the accelerometer I get a 050 error message on the micro bit. I've tried both micro bits that I have and they both get the same error.

Even the simplest blocks under the heading "To use a second micro:bit as a remote control" on https://makecode.microbit.org/pkg/dexterind/pxt-giggle give the same error message.

I've tried all of the firmwares (0241, 0249, 0250, and 0253) that are available on https://microbit.org/get-started/user-guide/firmware/ and get the same error message.

I find it unlikely to be a hardware issue as suggested by https://support.microbit.org/support/solutions/articles/19000097285-050 as other accelerometer usage not using this package works as expected. For example using the standard input > on tilt left/right etc blocks I am able to get it to work without the 050 error.

**Comment by CleoQc** [comment]
It's happened before when a new version of Makecode comes up.  I had tested the new makecode and didn't detect anything. Obviously, there's something I missed. 

Can you give me a code sample?

**Comment by smsm1** [comment]
Giggle bot code:
<img width="1600" alt="Screenshot 2020-06-28 at 23 02 20" src="https://user-images.githubusercontent.com/82719/85959311-8a4f3800-b993-11ea-9a8f-122fae563bca.png">

Remote control code:
<img width="1600" alt="Screenshot 2020-06-28 at 23 02 36" src="https://user-images.githubusercontent.com/82719/85959322-9e933500-b993-11ea-8f5e-8525444b8ead.png">

Code as downloaded from make code at https://makecode.microbit.org/#editor 
[gigglebot-remote-and-bot-code.zip](https://github.com/DexterInd/pxt-giggle/files/4843058/gigglebot-remote-and-bot-code.zip)

It's once I start tipping the remote control micro:bit that I get the sad face 050. On subsequent resets it happens straight away until I flash another program on to it.

**Comment by smsm1** [comment]
The issue has happened with both downloading from Google Chrome and Safari on macOS, and using Chromium on a Raspberry Pi.

**Comment by CleoQc** [comment]
Fixed with https://github.com/DexterInd/pxt-giggle/pull/22

Note that the microbit on the gigglebot cannot query the accelerometer, but at least the remote blocks should work.

**Comment by smsm1** [comment]
Thank you for the persistence and finding the issue and fix. I confirm that it's now working after re-adding the extension to the Makecode project. I've learnt numerous things though the comments on the linked tickets, thanks. :-)
