### ISSUE TITLE
_locales/giggle-jsdoc-strings.json - spelling errors

### ISSUE THREAD

**Issue by jharris1993** [DexterInd/pxt-giggle#26]
The file _locales/giggle-jsdoc-strings.json has a few spelling errors.
1.  "micro:bit" should not be capitalized.
2. In the radio section added necessary plurals, (s), and corrected the spelling of GiggleBot from "gigglebot"
3.

**Comment by CleoQc** [comment]
Thank you for your sharp eyes!
