### ISSUE TITLE
There is no block to control the eyes on the GiggleBot

### ISSUE THREAD

**Issue by jharris1993** [DexterInd/pxt-giggle#27]
It is not possible to control the eyes of the GiggleBot directly via MakeCode.

If you insert the following line into the JavaScript representation of the code.
```
lights.whichEye(gigglebotWhichEye.Both).showColor(neopixel.colors(NeoPixelColors.Green))
```
. . . it creates a psudo-block, (without a verb).

Viz.:
![Eyes what happens if I insert raw code](https://user-images.githubusercontent.com/12052596/166169402-57e5b501-68b4-4822-8c08-c1ef283e9dfc.jpg)

I am going to work on this.

**Comment by CleoQc** [comment]
This is intentional. The eyes are used to show battery level. They turn red if the batteries are running low.
